[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨${count}"
behind = "ğŸ¢${count}"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\(${count}\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
